$("#grupo_posicion").tabs();

$("#table_contado").jqGrid({
    datatype: "local",
    height: 250,
    colNames: [
        "Contrato",
        "Plazo",
        "Emisora",
        "Cantidad",
        "Costo",
        "Precio",
        "Inversion",
        "Valor",
        "Tasa",
        "%Tot",
        "%Inv",
        "Ult. Mov.",
        "Fec. Ve...",
        "Imp. Venc.",
        "Nat.",
        "ISR Dia"
    ],
    colModel: [
        { name: "contrato", width: 55 },
        { name: "plazo", width: 55 },
        { name: "emisora", width: 55 },
        { name: "cantidad", width: 55 },
        { name: "costo", width: 55 },
        { name: "precio", width: 55 },
        { name: "inversion", width: 55 },
        { name: "valor", width: 55 },
        { name: "tasa", width: 55 },
        { name: "tot", width: 55 },
        { name: "inv", width: 55 },
        { name: "ultMov", width: 55 },
        { name: "fecVe", width: 55 },
        { name: "impVenc", width: 55 },
        { name: "nat", width: 55 },
        { name: "isrDia", width: 55 }
    ],
    pager: "#pager_contado",
    rowNum: 10,
    rowList: [10, 20, 30],
    sortname: "tipo",
    sortorder: "desc",
    viewrecords: true,
    gridview: true,
    autoencode: true,
    caption: ""
});

$("#table_difgtia").jqGrid({
    datatype: "local",
    height: 250,
    colNames: [
        "Contrato",
        "Plazo",
        "Emisora",
        "Cantidad",
        "Costo",
        "Precio",
        "Inversion",
        "Valor",
        "Tasa",
        "%Tot",
        "%Inv",
        "Ult. Mov.",
        "Fec. Ve...",
        "Imp. Venc.",
        "Nat.",
        "ISR Dia"
    ],
    colModel: [
        { name: "contrato", width: 55 },
        { name: "plazo", width: 55 },
        { name: "emisora", width: 55 },
        { name: "cantidad", width: 55 },
        { name: "costo", width: 55 },
        { name: "precio", width: 55 },
        { name: "inversion", width: 55 },
        { name: "valor", width: 55 },
        { name: "tasa", width: 55 },
        { name: "tot", width: 55 },
        { name: "inv", width: 55 },
        { name: "ultMov", width: 55 },
        { name: "fecVe", width: 55 },
        { name: "impVenc", width: 55 },
        { name: "nat", width: 55 },
        { name: "isrDia", width: 55 }
    ],
    pager: "#pager_difgtia",
    rowNum: 10,
    rowList: [10, 20, 30],
    sortname: "tipo",
    sortorder: "desc",
    viewrecords: true,
    gridview: true,
    autoencode: true,
    caption: ""
});

$("#table_spc").jqGrid({
    datatype: "local",
    height: 250,
    colNames: [
        "Contrato",
        "Plazo",
        "Emisora",
        "Cantidad",
        "Costo",
        "Precio",
        "Inversion",
        "Valor",
        "Tasa",
        "%Tot",
        "%Inv",
        "Ult. Mov.",
        "Fec. Ve...",
        "Imp. Venc.",
        "Nat.",
        "ISR Dia"
    ],
    colModel: [
        { name: "contrato", width: 55 },
        { name: "plazo", width: 55 },
        { name: "emisora", width: 55 },
        { name: "cantidad", width: 55 },
        { name: "costo", width: 55 },
        { name: "precio", width: 55 },
        { name: "inversion", width: 55 },
        { name: "valor", width: 55 },
        { name: "tasa", width: 55 },
        { name: "tot", width: 55 },
        { name: "inv", width: 55 },
        { name: "ultMov", width: 55 },
        { name: "fecVe", width: 55 },
        { name: "impVenc", width: 55 },
        { name: "nat", width: 55 },
        { name: "isrDia", width: 55 }
    ],
    pager: "#pager_spc",
    rowNum: 10,
    rowList: [10, 20, 30],
    sortname: "tipo",
    sortorder: "desc",
    viewrecords: true,
    gridview: true,
    autoencode: true,
    caption: ""
});